### ISSUE TITLE
Collaboration with xcsoar/xcsoar-data-content ?

### ISSUE THREAD

**Issue by lordfolken** [whiteroom/landables_ch#11]
Hey!

I have already updated the data for Swiss Airfields here:
https://github.com/xcsoar/xcsoar-data-content

This is based on the old welt2000 data, as there seem to be no decent waypoint resources (for gliding). See also https://github.com/XCSoar/xcsoar-data-content/issues/13

I'd also love to carry the information available to XCSoar user via internal download manager.

Do you see a chance for collaboration?

**Comment by lordfolken** [comment]
We have a waypoint special file, which can feature pictures for each airfield. I would have to convert from PDF to bmp/png.

**Comment by whiteroom** [comment]
Sorry, I see little chance. I'm out of capacity for the moment…
